export const CUTE_ITEM_LIST = [
  {
    id: 1,
    name: "봉지",
    hashtag: ["말티피그", "장봉지", "7짤"],
    profile: "img/Bongji.jpg",
    category: "dog",
  },
  {
    id: 2,
    name: "밤비",
    hashtag: ["꼬똥", "3짤", "고창석"],
    profile: "img/Bambi.jpg",
    category: "dog",
  },
  {
    id: 3,
    name: "후지",
    hashtag: ["비숑", "강후지", "훚"],
    profile: "img/Huji.jpg",
    category: "dog",
  },
  {
    id: 4,
    name: "고영희 짤",
    hashtag: ["고얌이", "냥아치다"],
    profile: "img/Cat.JPG",
    category: "cat",
  },
  {
    id: 5,
    name: "행복한 쿼카",
    hashtag: ["셀카장인", "스마일", "호주"],
    profile: "img/Happy.jpg",
    category: "etc",
  },
  {
    id: 6,
    name: "춘식이",
    hashtag: ["카카오프렌즈 춘식", "따땃"],
    profile: "img/Chunsic.jpg",
    category: "etc",
  },
  {
    id: 7,
    name: "햄뿡이",
    hashtag: ["햄뿡이", "방구뿡뿡", "내취향"],
    profile: "img/Hambbung.jpg",
    category: "etc",
  },
  {
    id: 8,
    name: "최고심",
    hashtag: ["할수이따", "긍정!!!", "체고"],
    profile: "img/Gosim.JPG",
    category: "etc",
  },
  {
    id: 9,
    name: "명지",
    hashtag: ["_myundi", "귀욤짱", "25짤", "요정"],
    profile: "img/Myungji.jpg",
    category: "etc",
  },
  {
    id: 10,
    name: "햄찌짤",
    hashtag: ["햄스터", "따봉짤", "최애짤"],
    profile: "img/Hamjji.JPG",
    category: "etc",
  },
];
